/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthUsersRouteImport } from "./routes/_auth/users.tsx";
import { Route as AuthGlobalSplatRouteImport } from "./routes/_auth/global.$.tsx";
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects.index.tsx";
import { Route as AuthProjectsSlugSplatRouteImport } from "./routes/_auth/projects.$slug.$.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthRoute,
} as any);
const AuthGlobalSplatRoute = AuthGlobalSplatRouteImport.update({
  id: "/global/$",
  path: "/global/$",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsSlugSplatRoute = AuthProjectsSlugSplatRouteImport.update({
  id: "/projects/$slug/$",
  path: "/projects/$slug/$",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/users": typeof AuthUsersRoute;
  "/global/$": typeof AuthGlobalSplatRoute;
  "/projects/": typeof AuthProjectsIndexRoute;
  "/projects/$slug/$": typeof AuthProjectsSlugSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/users": typeof AuthUsersRoute;
  "/global/$": typeof AuthGlobalSplatRoute;
  "/projects": typeof AuthProjectsIndexRoute;
  "/projects/$slug/$": typeof AuthProjectsSlugSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/users": typeof AuthUsersRoute;
  "/_auth/global/$": typeof AuthGlobalSplatRoute;
  "/_auth/projects/": typeof AuthProjectsIndexRoute;
  "/_auth/projects/$slug/$": typeof AuthProjectsSlugSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/users" | "/global/$" | "/projects/" | "/projects/$slug/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/users" | "/global/$" | "/projects" | "/projects/$slug/$";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/users"
    | "/_auth/global/$"
    | "/_auth/projects/"
    | "/_auth/projects/$slug/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/users": {
      id: "/_auth/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof AuthUsersRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/global/$": {
      id: "/_auth/global/$";
      path: "/global/$";
      fullPath: "/global/$";
      preLoaderRoute: typeof AuthGlobalSplatRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/": {
      id: "/_auth/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof AuthProjectsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug/$": {
      id: "/_auth/projects/$slug/$";
      path: "/projects/$slug/$";
      fullPath: "/projects/$slug/$";
      preLoaderRoute: typeof AuthProjectsSlugSplatRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthUsersRoute: typeof AuthUsersRoute;
  AuthGlobalSplatRoute: typeof AuthGlobalSplatRoute;
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute;
  AuthProjectsSlugSplatRoute: typeof AuthProjectsSlugSplatRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUsersRoute: AuthUsersRoute,
  AuthGlobalSplatRoute: AuthGlobalSplatRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsSlugSplatRoute: AuthProjectsSlugSplatRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
