/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects.index.tsx";
import { Route as AuthProjectsSlugRouteImport } from "./routes/_auth/projects.$slug.tsx";
import { Route as AuthProjectsSlugIndexRouteImport } from "./routes/_auth/projects.$slug.index.tsx";
import { Route as AuthProjectsSlugRepoIndexRouteImport } from "./routes/_auth/projects.$slug.$repo.index.tsx";
import { Route as AuthProjectsSlugRepoSplatRouteImport } from "./routes/_auth/projects.$slug.$repo.$.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsSlugRoute = AuthProjectsSlugRouteImport.update({
  id: "/projects/$slug",
  path: "/projects/$slug",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsSlugIndexRoute = AuthProjectsSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthProjectsSlugRoute,
} as any);
const AuthProjectsSlugRepoIndexRoute =
  AuthProjectsSlugRepoIndexRouteImport.update({
    id: "/$repo/",
    path: "/$repo/",
    getParentRoute: () => AuthProjectsSlugRoute,
  } as any);
const AuthProjectsSlugRepoSplatRoute =
  AuthProjectsSlugRepoSplatRouteImport.update({
    id: "/$repo/$",
    path: "/$repo/$",
    getParentRoute: () => AuthProjectsSlugRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/projects/$slug": typeof AuthProjectsSlugRouteWithChildren;
  "/projects/": typeof AuthProjectsIndexRoute;
  "/projects/$slug/": typeof AuthProjectsSlugIndexRoute;
  "/projects/$slug/$repo/$": typeof AuthProjectsSlugRepoSplatRoute;
  "/projects/$slug/$repo/": typeof AuthProjectsSlugRepoIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/projects": typeof AuthProjectsIndexRoute;
  "/projects/$slug": typeof AuthProjectsSlugIndexRoute;
  "/projects/$slug/$repo/$": typeof AuthProjectsSlugRepoSplatRoute;
  "/projects/$slug/$repo": typeof AuthProjectsSlugRepoIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/projects/$slug": typeof AuthProjectsSlugRouteWithChildren;
  "/_auth/projects/": typeof AuthProjectsIndexRoute;
  "/_auth/projects/$slug/": typeof AuthProjectsSlugIndexRoute;
  "/_auth/projects/$slug/$repo/$": typeof AuthProjectsSlugRepoSplatRoute;
  "/_auth/projects/$slug/$repo/": typeof AuthProjectsSlugRepoIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/projects/$slug"
    | "/projects/"
    | "/projects/$slug/"
    | "/projects/$slug/$repo/$"
    | "/projects/$slug/$repo/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/projects"
    | "/projects/$slug"
    | "/projects/$slug/$repo/$"
    | "/projects/$slug/$repo";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/projects/$slug"
    | "/_auth/projects/"
    | "/_auth/projects/$slug/"
    | "/_auth/projects/$slug/$repo/$"
    | "/_auth/projects/$slug/$repo/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/projects/": {
      id: "/_auth/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof AuthProjectsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug": {
      id: "/_auth/projects/$slug";
      path: "/projects/$slug";
      fullPath: "/projects/$slug";
      preLoaderRoute: typeof AuthProjectsSlugRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug/": {
      id: "/_auth/projects/$slug/";
      path: "/";
      fullPath: "/projects/$slug/";
      preLoaderRoute: typeof AuthProjectsSlugIndexRouteImport;
      parentRoute: typeof AuthProjectsSlugRoute;
    };
    "/_auth/projects/$slug/$repo/": {
      id: "/_auth/projects/$slug/$repo/";
      path: "/$repo";
      fullPath: "/projects/$slug/$repo/";
      preLoaderRoute: typeof AuthProjectsSlugRepoIndexRouteImport;
      parentRoute: typeof AuthProjectsSlugRoute;
    };
    "/_auth/projects/$slug/$repo/$": {
      id: "/_auth/projects/$slug/$repo/$";
      path: "/$repo/$";
      fullPath: "/projects/$slug/$repo/$";
      preLoaderRoute: typeof AuthProjectsSlugRepoSplatRouteImport;
      parentRoute: typeof AuthProjectsSlugRoute;
    };
  }
}

interface AuthProjectsSlugRouteChildren {
  AuthProjectsSlugIndexRoute: typeof AuthProjectsSlugIndexRoute;
  AuthProjectsSlugRepoSplatRoute: typeof AuthProjectsSlugRepoSplatRoute;
  AuthProjectsSlugRepoIndexRoute: typeof AuthProjectsSlugRepoIndexRoute;
}

const AuthProjectsSlugRouteChildren: AuthProjectsSlugRouteChildren = {
  AuthProjectsSlugIndexRoute: AuthProjectsSlugIndexRoute,
  AuthProjectsSlugRepoSplatRoute: AuthProjectsSlugRepoSplatRoute,
  AuthProjectsSlugRepoIndexRoute: AuthProjectsSlugRepoIndexRoute,
};

const AuthProjectsSlugRouteWithChildren =
  AuthProjectsSlugRoute._addFileChildren(AuthProjectsSlugRouteChildren);

interface AuthRouteChildren {
  AuthProjectsSlugRoute: typeof AuthProjectsSlugRouteWithChildren;
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjectsSlugRoute: AuthProjectsSlugRouteWithChildren,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
