/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects.index.tsx";
import { Route as AuthProjectsSlugRouteImport } from "./routes/_auth/projects.$slug.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsSlugRoute = AuthProjectsSlugRouteImport.update({
  id: "/projects/$slug",
  path: "/projects/$slug",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/projects/$slug": typeof AuthProjectsSlugRoute;
  "/projects/": typeof AuthProjectsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/projects/$slug": typeof AuthProjectsSlugRoute;
  "/projects": typeof AuthProjectsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/projects/$slug": typeof AuthProjectsSlugRoute;
  "/_auth/projects/": typeof AuthProjectsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/projects/$slug" | "/projects/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/projects/$slug" | "/projects";
  id:
    "__root__" | "/" | "/_auth" | "/_auth/projects/$slug" | "/_auth/projects/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/projects/": {
      id: "/_auth/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof AuthProjectsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug": {
      id: "/_auth/projects/$slug";
      path: "/projects/$slug";
      fullPath: "/projects/$slug";
      preLoaderRoute: typeof AuthProjectsSlugRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthProjectsSlugRoute: typeof AuthProjectsSlugRoute;
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjectsSlugRoute: AuthProjectsSlugRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
