/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthActivityRouteImport } from "./routes/_auth/activity.tsx";
import { Route as AuthHomeRouteImport } from "./routes/_auth/home.tsx";
import { Route as AuthSessionsRouteImport } from "./routes/_auth/sessions.tsx";
import { Route as CollectSecretSlugRouteImport } from "./routes/collect-secret.$slug.tsx";
import { Route as AuthInvitationsTokenRouteImport } from "./routes/_auth/invitations.$token.tsx";
import { Route as AuthOrganizationsIndexRouteImport } from "./routes/_auth/organizations/index.tsx";
import { Route as AuthOrganizationsOrgIdRouteImport } from "./routes/_auth/organizations/$orgId.tsx";
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects/index.tsx";
import { Route as AuthProjectsSlugRouteRouteImport } from "./routes/_auth/projects/$slug/route.tsx";
import { Route as AuthOrganizationsOrgIdActivityRouteImport } from "./routes/_auth/organizations/$orgId_.activity.tsx";
import { Route as AuthProjectsSlugIndexRouteImport } from "./routes/_auth/projects/$slug/index.tsx";
import { Route as AuthProjectsSlugDomainsRouteImport } from "./routes/_auth/projects/$slug/domains.tsx";
import { Route as AuthProjectsSlugIntegrationsRouteImport } from "./routes/_auth/projects/$slug/integrations.tsx";
import { Route as AuthProjectsSlugMcpRouteImport } from "./routes/_auth/projects/$slug/mcp.tsx";
import { Route as AuthProjectsSlugSecretsRouteImport } from "./routes/_auth/projects/$slug/secrets.tsx";
import { Route as AuthProjectsSlugContextsSplatRouteImport } from "./routes/_auth/projects/$slug/contexts.$.tsx";
import { Route as AuthProjectsSlugReposIndexRouteImport } from "./routes/_auth/projects/$slug/repos.index.tsx";
import { Route as AuthProjectsSlugReposSplatRouteImport } from "./routes/_auth/projects/$slug/repos.$.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthActivityRoute = AuthActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => AuthRoute,
} as any);
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => AuthRoute,
} as any);
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => AuthRoute,
} as any);
const CollectSecretSlugRoute = CollectSecretSlugRouteImport.update({
  id: "/collect-secret/$slug",
  path: "/collect-secret/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthInvitationsTokenRoute = AuthInvitationsTokenRouteImport.update({
  id: "/invitations/$token",
  path: "/invitations/$token",
  getParentRoute: () => AuthRoute,
} as any);
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: "/organizations/",
  path: "/organizations/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthOrganizationsOrgIdRoute = AuthOrganizationsOrgIdRouteImport.update({
  id: "/organizations/$orgId",
  path: "/organizations/$orgId",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthProjectsSlugRouteRoute = AuthProjectsSlugRouteRouteImport.update({
  id: "/projects/$slug",
  path: "/projects/$slug",
  getParentRoute: () => AuthRoute,
} as any);
const AuthOrganizationsOrgIdActivityRoute =
  AuthOrganizationsOrgIdActivityRouteImport.update({
    id: "/organizations/$orgId_/activity",
    path: "/organizations/$orgId/activity",
    getParentRoute: () => AuthRoute,
  } as any);
const AuthProjectsSlugIndexRoute = AuthProjectsSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthProjectsSlugRouteRoute,
} as any);
const AuthProjectsSlugDomainsRoute = AuthProjectsSlugDomainsRouteImport.update({
  id: "/domains",
  path: "/domains",
  getParentRoute: () => AuthProjectsSlugRouteRoute,
} as any);
const AuthProjectsSlugIntegrationsRoute =
  AuthProjectsSlugIntegrationsRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => AuthProjectsSlugRouteRoute,
  } as any);
const AuthProjectsSlugMcpRoute = AuthProjectsSlugMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => AuthProjectsSlugRouteRoute,
} as any);
const AuthProjectsSlugSecretsRoute = AuthProjectsSlugSecretsRouteImport.update({
  id: "/secrets",
  path: "/secrets",
  getParentRoute: () => AuthProjectsSlugRouteRoute,
} as any);
const AuthProjectsSlugContextsSplatRoute =
  AuthProjectsSlugContextsSplatRouteImport.update({
    id: "/contexts/$",
    path: "/contexts/$",
    getParentRoute: () => AuthProjectsSlugRouteRoute,
  } as any);
const AuthProjectsSlugReposIndexRoute =
  AuthProjectsSlugReposIndexRouteImport.update({
    id: "/repos/",
    path: "/repos/",
    getParentRoute: () => AuthProjectsSlugRouteRoute,
  } as any);
const AuthProjectsSlugReposSplatRoute =
  AuthProjectsSlugReposSplatRouteImport.update({
    id: "/repos/$",
    path: "/repos/$",
    getParentRoute: () => AuthProjectsSlugRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/activity": typeof AuthActivityRoute;
  "/home": typeof AuthHomeRoute;
  "/sessions": typeof AuthSessionsRoute;
  "/collect-secret/$slug": typeof CollectSecretSlugRoute;
  "/projects/$slug": typeof AuthProjectsSlugRouteRouteWithChildren;
  "/invitations/$token": typeof AuthInvitationsTokenRoute;
  "/organizations/$orgId": typeof AuthOrganizationsOrgIdRoute;
  "/organizations/": typeof AuthOrganizationsIndexRoute;
  "/projects/": typeof AuthProjectsIndexRoute;
  "/organizations/$orgId/activity": typeof AuthOrganizationsOrgIdActivityRoute;
  "/projects/$slug/domains": typeof AuthProjectsSlugDomainsRoute;
  "/projects/$slug/integrations": typeof AuthProjectsSlugIntegrationsRoute;
  "/projects/$slug/mcp": typeof AuthProjectsSlugMcpRoute;
  "/projects/$slug/secrets": typeof AuthProjectsSlugSecretsRoute;
  "/projects/$slug/": typeof AuthProjectsSlugIndexRoute;
  "/projects/$slug/contexts/$": typeof AuthProjectsSlugContextsSplatRoute;
  "/projects/$slug/repos/$": typeof AuthProjectsSlugReposSplatRoute;
  "/projects/$slug/repos/": typeof AuthProjectsSlugReposIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/activity": typeof AuthActivityRoute;
  "/home": typeof AuthHomeRoute;
  "/sessions": typeof AuthSessionsRoute;
  "/collect-secret/$slug": typeof CollectSecretSlugRoute;
  "/invitations/$token": typeof AuthInvitationsTokenRoute;
  "/organizations/$orgId": typeof AuthOrganizationsOrgIdRoute;
  "/organizations": typeof AuthOrganizationsIndexRoute;
  "/projects": typeof AuthProjectsIndexRoute;
  "/organizations/$orgId/activity": typeof AuthOrganizationsOrgIdActivityRoute;
  "/projects/$slug/domains": typeof AuthProjectsSlugDomainsRoute;
  "/projects/$slug/integrations": typeof AuthProjectsSlugIntegrationsRoute;
  "/projects/$slug/mcp": typeof AuthProjectsSlugMcpRoute;
  "/projects/$slug/secrets": typeof AuthProjectsSlugSecretsRoute;
  "/projects/$slug": typeof AuthProjectsSlugIndexRoute;
  "/projects/$slug/contexts/$": typeof AuthProjectsSlugContextsSplatRoute;
  "/projects/$slug/repos/$": typeof AuthProjectsSlugReposSplatRoute;
  "/projects/$slug/repos": typeof AuthProjectsSlugReposIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/activity": typeof AuthActivityRoute;
  "/_auth/home": typeof AuthHomeRoute;
  "/_auth/sessions": typeof AuthSessionsRoute;
  "/collect-secret/$slug": typeof CollectSecretSlugRoute;
  "/_auth/projects/$slug": typeof AuthProjectsSlugRouteRouteWithChildren;
  "/_auth/invitations/$token": typeof AuthInvitationsTokenRoute;
  "/_auth/organizations/$orgId": typeof AuthOrganizationsOrgIdRoute;
  "/_auth/organizations/": typeof AuthOrganizationsIndexRoute;
  "/_auth/projects/": typeof AuthProjectsIndexRoute;
  "/_auth/organizations/$orgId_/activity": typeof AuthOrganizationsOrgIdActivityRoute;
  "/_auth/projects/$slug/domains": typeof AuthProjectsSlugDomainsRoute;
  "/_auth/projects/$slug/integrations": typeof AuthProjectsSlugIntegrationsRoute;
  "/_auth/projects/$slug/mcp": typeof AuthProjectsSlugMcpRoute;
  "/_auth/projects/$slug/secrets": typeof AuthProjectsSlugSecretsRoute;
  "/_auth/projects/$slug/": typeof AuthProjectsSlugIndexRoute;
  "/_auth/projects/$slug/contexts/$": typeof AuthProjectsSlugContextsSplatRoute;
  "/_auth/projects/$slug/repos/$": typeof AuthProjectsSlugReposSplatRoute;
  "/_auth/projects/$slug/repos/": typeof AuthProjectsSlugReposIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/activity"
    | "/home"
    | "/sessions"
    | "/collect-secret/$slug"
    | "/projects/$slug"
    | "/invitations/$token"
    | "/organizations/$orgId"
    | "/organizations/"
    | "/projects/"
    | "/organizations/$orgId/activity"
    | "/projects/$slug/domains"
    | "/projects/$slug/integrations"
    | "/projects/$slug/mcp"
    | "/projects/$slug/secrets"
    | "/projects/$slug/"
    | "/projects/$slug/contexts/$"
    | "/projects/$slug/repos/$"
    | "/projects/$slug/repos/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/activity"
    | "/home"
    | "/sessions"
    | "/collect-secret/$slug"
    | "/invitations/$token"
    | "/organizations/$orgId"
    | "/organizations"
    | "/projects"
    | "/organizations/$orgId/activity"
    | "/projects/$slug/domains"
    | "/projects/$slug/integrations"
    | "/projects/$slug/mcp"
    | "/projects/$slug/secrets"
    | "/projects/$slug"
    | "/projects/$slug/contexts/$"
    | "/projects/$slug/repos/$"
    | "/projects/$slug/repos";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/activity"
    | "/_auth/home"
    | "/_auth/sessions"
    | "/collect-secret/$slug"
    | "/_auth/projects/$slug"
    | "/_auth/invitations/$token"
    | "/_auth/organizations/$orgId"
    | "/_auth/organizations/"
    | "/_auth/projects/"
    | "/_auth/organizations/$orgId_/activity"
    | "/_auth/projects/$slug/domains"
    | "/_auth/projects/$slug/integrations"
    | "/_auth/projects/$slug/mcp"
    | "/_auth/projects/$slug/secrets"
    | "/_auth/projects/$slug/"
    | "/_auth/projects/$slug/contexts/$"
    | "/_auth/projects/$slug/repos/$"
    | "/_auth/projects/$slug/repos/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  CollectSecretSlugRoute: typeof CollectSecretSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/activity": {
      id: "/_auth/activity";
      path: "/activity";
      fullPath: "/activity";
      preLoaderRoute: typeof AuthActivityRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/home": {
      id: "/_auth/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof AuthHomeRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/sessions": {
      id: "/_auth/sessions";
      path: "/sessions";
      fullPath: "/sessions";
      preLoaderRoute: typeof AuthSessionsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/collect-secret/$slug": {
      id: "/collect-secret/$slug";
      path: "/collect-secret/$slug";
      fullPath: "/collect-secret/$slug";
      preLoaderRoute: typeof CollectSecretSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/invitations/$token": {
      id: "/_auth/invitations/$token";
      path: "/invitations/$token";
      fullPath: "/invitations/$token";
      preLoaderRoute: typeof AuthInvitationsTokenRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/organizations/": {
      id: "/_auth/organizations/";
      path: "/organizations";
      fullPath: "/organizations/";
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/organizations/$orgId": {
      id: "/_auth/organizations/$orgId";
      path: "/organizations/$orgId";
      fullPath: "/organizations/$orgId";
      preLoaderRoute: typeof AuthOrganizationsOrgIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/": {
      id: "/_auth/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof AuthProjectsIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug": {
      id: "/_auth/projects/$slug";
      path: "/projects/$slug";
      fullPath: "/projects/$slug";
      preLoaderRoute: typeof AuthProjectsSlugRouteRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/organizations/$orgId_/activity": {
      id: "/_auth/organizations/$orgId_/activity";
      path: "/organizations/$orgId/activity";
      fullPath: "/organizations/$orgId/activity";
      preLoaderRoute: typeof AuthOrganizationsOrgIdActivityRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/projects/$slug/": {
      id: "/_auth/projects/$slug/";
      path: "/";
      fullPath: "/projects/$slug/";
      preLoaderRoute: typeof AuthProjectsSlugIndexRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/domains": {
      id: "/_auth/projects/$slug/domains";
      path: "/domains";
      fullPath: "/projects/$slug/domains";
      preLoaderRoute: typeof AuthProjectsSlugDomainsRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/integrations": {
      id: "/_auth/projects/$slug/integrations";
      path: "/integrations";
      fullPath: "/projects/$slug/integrations";
      preLoaderRoute: typeof AuthProjectsSlugIntegrationsRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/mcp": {
      id: "/_auth/projects/$slug/mcp";
      path: "/mcp";
      fullPath: "/projects/$slug/mcp";
      preLoaderRoute: typeof AuthProjectsSlugMcpRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/secrets": {
      id: "/_auth/projects/$slug/secrets";
      path: "/secrets";
      fullPath: "/projects/$slug/secrets";
      preLoaderRoute: typeof AuthProjectsSlugSecretsRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/contexts/$": {
      id: "/_auth/projects/$slug/contexts/$";
      path: "/contexts/$";
      fullPath: "/projects/$slug/contexts/$";
      preLoaderRoute: typeof AuthProjectsSlugContextsSplatRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/repos/": {
      id: "/_auth/projects/$slug/repos/";
      path: "/repos";
      fullPath: "/projects/$slug/repos/";
      preLoaderRoute: typeof AuthProjectsSlugReposIndexRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
    "/_auth/projects/$slug/repos/$": {
      id: "/_auth/projects/$slug/repos/$";
      path: "/repos/$";
      fullPath: "/projects/$slug/repos/$";
      preLoaderRoute: typeof AuthProjectsSlugReposSplatRouteImport;
      parentRoute: typeof AuthProjectsSlugRouteRoute;
    };
  }
}

interface AuthProjectsSlugRouteRouteChildren {
  AuthProjectsSlugDomainsRoute: typeof AuthProjectsSlugDomainsRoute;
  AuthProjectsSlugIntegrationsRoute: typeof AuthProjectsSlugIntegrationsRoute;
  AuthProjectsSlugMcpRoute: typeof AuthProjectsSlugMcpRoute;
  AuthProjectsSlugSecretsRoute: typeof AuthProjectsSlugSecretsRoute;
  AuthProjectsSlugIndexRoute: typeof AuthProjectsSlugIndexRoute;
  AuthProjectsSlugContextsSplatRoute: typeof AuthProjectsSlugContextsSplatRoute;
  AuthProjectsSlugReposSplatRoute: typeof AuthProjectsSlugReposSplatRoute;
  AuthProjectsSlugReposIndexRoute: typeof AuthProjectsSlugReposIndexRoute;
}

const AuthProjectsSlugRouteRouteChildren: AuthProjectsSlugRouteRouteChildren = {
  AuthProjectsSlugDomainsRoute: AuthProjectsSlugDomainsRoute,
  AuthProjectsSlugIntegrationsRoute: AuthProjectsSlugIntegrationsRoute,
  AuthProjectsSlugMcpRoute: AuthProjectsSlugMcpRoute,
  AuthProjectsSlugSecretsRoute: AuthProjectsSlugSecretsRoute,
  AuthProjectsSlugIndexRoute: AuthProjectsSlugIndexRoute,
  AuthProjectsSlugContextsSplatRoute: AuthProjectsSlugContextsSplatRoute,
  AuthProjectsSlugReposSplatRoute: AuthProjectsSlugReposSplatRoute,
  AuthProjectsSlugReposIndexRoute: AuthProjectsSlugReposIndexRoute,
};

const AuthProjectsSlugRouteRouteWithChildren =
  AuthProjectsSlugRouteRoute._addFileChildren(
    AuthProjectsSlugRouteRouteChildren,
  );

interface AuthRouteChildren {
  AuthActivityRoute: typeof AuthActivityRoute;
  AuthHomeRoute: typeof AuthHomeRoute;
  AuthSessionsRoute: typeof AuthSessionsRoute;
  AuthProjectsSlugRouteRoute: typeof AuthProjectsSlugRouteRouteWithChildren;
  AuthInvitationsTokenRoute: typeof AuthInvitationsTokenRoute;
  AuthOrganizationsOrgIdRoute: typeof AuthOrganizationsOrgIdRoute;
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute;
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute;
  AuthOrganizationsOrgIdActivityRoute: typeof AuthOrganizationsOrgIdActivityRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivityRoute: AuthActivityRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthSessionsRoute: AuthSessionsRoute,
  AuthProjectsSlugRouteRoute: AuthProjectsSlugRouteRouteWithChildren,
  AuthInvitationsTokenRoute: AuthInvitationsTokenRoute,
  AuthOrganizationsOrgIdRoute: AuthOrganizationsOrgIdRoute,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthOrganizationsOrgIdActivityRoute: AuthOrganizationsOrgIdActivityRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CollectSecretSlugRoute: CollectSecretSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
